<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[setLoginPageEmailId]]>
    </line>
    <line>
      <![CDATA[setLoginPagePassword]]>
    </line>
    <line>
      <![CDATA[clickLoginPageLoginBtn]]>
    </line>
  </reporter-output>
  <suite started-at="2022-11-13T09:03:32Z" name="Default suite" finished-at="2022-11-13T09:03:48Z" duration-ms="16417">
    <groups>
    </groups>
    <test started-at="2022-11-13T09:03:32Z" name="Default test" finished-at="2022-11-13T09:03:48Z" duration-ms="16417">
      <class name="cc.minimals.qa.TestCases.MinimalUIPageTest">
        <test-method is-config="true" signature="setup()" started-at="2022-11-13T09:03:32Z" name="setup" finished-at="2022-11-13T09:03:45Z" duration-ms="12956" status="PASS">
        </test-method>
        <test-method signature="MininmalUIPageLogoutTest()" started-at="2022-11-13T09:03:45Z" name="MininmalUIPageLogoutTest" finished-at="2022-11-13T09:03:48Z" duration-ms="3436" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<https://minimals.cc/dashboard/app> but was:<https://minimals.cc/auth/login-unprotected>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<https://minimals.cc/dashboard/app> but was:<https://minimals.cc/auth/login-unprotected>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:171)
	at org.testng.Assert.assertEquals(Assert.java:181)
	at cc.minimals.qa.Pages.MinimalUIPage.verifyMinimalUICurrentUrl(MinimalUIPage.java:29)
	at cc.minimals.qa.TestCases.MinimalUIPageTest.MininmalUIPageLogoutTest(MinimalUIPageTest.java:38)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:842)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1166)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1178)
	at org.testng.TestRunner.privateRun(TestRunner.java:757)
	at org.testng.TestRunner.run(TestRunner.java:608)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
	at org.testng.TestNG.run(TestNG.java:999)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
      </class>
    </test>
  </suite>
</testng-results>
